<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SwarupKshatriya" failures="0" tests="4" name="testRunnerFile.TestRunnerForVehicleInsurance" time="2.720" errors="3" timestamp="2024-07-16T17:22:52 EDT" skipped="1">
  <testcase classname="testRunnerFile.TestRunnerForVehicleInsurance" name="TestCase4" time="0.906">
    <error message="userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y
at testRunnerFile.TestRunnerForVehicleInsurance.TestCase4(TestRunnerForVehicleInsurance.java:186)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y
at testdatareader.TestDataReader.checkTestDataFile(TestDataReader.java:139)
at testdatareader.TestDataReader.readTestData(TestDataReader.java:64)
at testRunnerFile.TestRunnerForVehicleInsurance.TestCase4(TestRunnerForVehicleInsurance.java:184)
... 18 more
]]>
    </error>
  </testcase> <!-- TestCase4 -->
  <testcase classname="testRunnerFile.TestRunnerForVehicleInsurance" name="TestCase2" time="0.906">
    <error message="userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y
at testRunnerFile.TestRunnerForVehicleInsurance.TestCase2(TestRunnerForVehicleInsurance.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y
at testdatareader.TestDataReader.checkTestDataFile(TestDataReader.java:139)
at testdatareader.TestDataReader.readTestData(TestDataReader.java:64)
at testRunnerFile.TestRunnerForVehicleInsurance.TestCase2(TestRunnerForVehicleInsurance.java:87)
... 18 more
]]>
    </error>
  </testcase> <!-- TestCase2 -->
  <testcase classname="testRunnerFile.TestRunnerForVehicleInsurance" name="TestCase3" time="0.007">
    <skipped/>
  </testcase> <!-- TestCase3 -->
  <testcase classname="testRunnerFile.TestRunnerForVehicleInsurance" name="TestCase1" time="0.901">
    <error message="userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y
at testRunnerFile.TestRunnerForVehicleInsurance.TestCase1(TestRunnerForVehicleInsurance.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: userdefinedExceptions.TestCaseOrFlagNotFoundException: Either Test Case Name is not matching or Flag is not set as Y
at testdatareader.TestDataReader.checkTestDataFile(TestDataReader.java:139)
at testdatareader.TestDataReader.readTestData(TestDataReader.java:64)
at testRunnerFile.TestRunnerForVehicleInsurance.TestCase1(TestRunnerForVehicleInsurance.java:38)
... 18 more
]]>
    </error>
  </testcase> <!-- TestCase1 -->
</testsuite> <!-- testRunnerFile.TestRunnerForVehicleInsurance -->
